version: "3"

services:
  service-mysql-main:
    image: mysql:8.0
    volumes:
      - ../../service-mysql/db-schema:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: service-mysql
      MYSQL_USER: service-mysql
      MYSQL_PASSWORD: service-mysql
      MYSQL_DATABASE: demoservice
    ports:
      - 13306:3306
  service-mysql-feature-1:
    image: mysql:8.0
    volumes:
      - ../../service-mysql/db-schema:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: service-mysql
      MYSQL_USER: service-mysql
      MYSQL_PASSWORD: service-mysql
      MYSQL_DATABASE: demoservice
    ports:
      - 13307:3306
  service-mysql-feature-2:
    image: mysql:8.0
    volumes:
      - ../../service-mysql/db-schema:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: service-mysql
      MYSQL_USER: service-mysql
      MYSQL_PASSWORD: service-mysql
      MYSQL_DATABASE: demoservice
    ports:
      - 13308:3306
