apiVersion: v1
kind: Namespace
metadata:
  name: picop-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-c
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-mysql
