apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-controller
  namespace: picop-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-controller
  template:
    metadata:
      labels:
        app: proxy-controller
    spec:
      containers:
        - name: proxy-controller
          image: "ghcr.io/picop-rd/proxy-controller:latest"
          command: ['/bin/proxy-controller', '--port', '8080', '--mysql', 'picop:picop@tcp(192.168.0.4:3306)/picop?parseTime=true&collation=utf8mb4_bin', '--interval', '10']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-controller
  namespace: picop-system
spec:
  type: NodePort
  selector:
    app: proxy-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
