apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-b
  namespace: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-b
  template:
    metadata:
      labels:
        app: proxy-b
    spec:
      containers:
        - name: proxy
          image: "ghcr.io/picop-rd/proxy:latest"
          command: ['/bin/proxy', '--proxy-port', '80', '--admin-port', '9000', '--default-addr', 'service-b-main.service-b.svc.cluster.local:80', '--propagate=true', '--controller-url', 'http://proxy-controller.picop-system.svc.cluster.local:8080', '--id', 'service-b']
          imagePullPolicy: Always
          ports:
            - name: proxy
              containerPort: 80
            - name: admin
              containerPort: 9000
      imagePullSecrets:
        - name: ghcrcred

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-b
  namespace: service-b
spec:
  type: NodePort
  selector:
    app: proxy-b
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 80
    - name: admin
      protocol: TCP
      port: 9000
      targetPort: 9000
