apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-controller
  namespace: bcop-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-controller
  template:
    metadata:
      labels:
        app: proxy-controller
    spec:
      containers:
        - name: proxy-controller
          image: "ghcr.io/hiroyaonoe/bcop-proxy-controller/bcop-proxy-controller:latest"
          command: ['/bin/bcop-proxy-controller', '--port', '8080', '--mysql', 'bcop:bcop@tcp(10.229.71.129:3306)/bcop?parseTime=true&collation=utf8mb4_bin', '--interval', '10']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-controller
  namespace: bcop-system
spec:
  type: NodePort
  selector:
    app: proxy-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
