apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-$(ENV)
  namespace: service-b
  labels:
    env: $(ENV)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b-$(ENV)
  template:
    metadata:
      labels:
        app: service-b-$(ENV)
    spec:
      containers:
        - name: service-b
          image: "ghcr.io/hiroyaonoe/bcop/bcop-demo-service-b:latest"
          command: ['/bin/service-b', '--port', '80', '--child-service', 'http://proxy-c.service-c.svc.cluster.local:80', '--message', 'This is service-b-$(ENV)']
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcrcred
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-$(ENV)
  namespace: service-b
spec:
  type: NodePort
  selector:
    app: service-b-$(ENV)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
