apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c-$(ENV)
  namespace: service-c
  labels:
    env: $(ENV)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c-$(ENV)
  template:
    metadata:
      labels:
        app: service-c-$(ENV)
    spec:
      containers:
        - name: service-c
          image: "ghcr.io/picop-rd/demo/service-c:latest"
          command: ['/bin/service-c', '--port', '80', '--mysql-service', 'service-mysql:service-mysql@tcp(proxy-mysql.service-mysql.svc.cluster.local:3306)/demoservice?parseTime=true&collation=utf8mb4_bin', '--message', 'This is service-c-$(ENV)']
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-c-$(ENV)
  namespace: service-c
spec:
  type: NodePort
  selector:
    app: service-c-$(ENV)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
